name: 🎵 Update Last.fm Stats

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-lastfm:
    name: Update Music Stats
    runs-on: ubuntu-latest
    steps:
      - name: Update Last.fm README
        uses: dxnter/lastfm-readme@v1
        with:
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
          LASTFM_USER: smarrtkidzee
          COMMIT_MESSAGE: 'chore: update last.fm stats'
          SHOW_TITLE: false
